### ISSUE TITLE
github.com/conformal/goleveldb not found

### ISSUE THREAD

**Issue by Thireus** [kac-/umint#1]
The following repository doesn't exist anymore: github.com/conformal/goleveldb
It was used in findstake:
- https://github.com/kac-/umint/blob/master/tools/findstake/find.go
- https://github.com/kac-/umint/blob/master/tools/findstake/findchain.go
- https://github.com/kac-/umint/blob/master/utxo/utxo.go

**Comment by Thireus** [comment]
github.com/syndtr/goleveldb can be used instead

**Comment by kac-** [comment]
Does it work with syndtr version?

**Comment by Thireus** [comment]
Yes it does

**Comment by mably** [comment]
Official Conformal goleveldb has been moved here: github.com/btcsuite/goleveldb

**Comment by Thireus** [comment]
Thank you mably, let me fix this.

**Comment by mably** [comment]
In fact the whole Conformal btcd project has been moved to the new btcsuite github organization: https://github.com/btcsuite
All conformal imports must be updated.

**Comment by Thireus** [comment]
Fixed :)
